Fix "Unknown 'maven' property" Error
octopusden/octopus-license-gradle-plugin pull request #11
Opened 2024-10-04 03:37 UTC by adellinekania

**Error:**
After switching to the hybrid flow https://github.com/octopusden/octopus-license-gradle-plugin/pull/8 & https://github.com/octopusden/octopus-license-gradle-plugin/pull/10, a bug was found when a project applied both the `octopus-release-management` and `octopus-license-gradle-plugin`:

```
groovy.lang.MissingPropertyException: Could not set unknown property 'maven' for object of type org.jfrog.gradle.plugin.artifactory.dsl.PublisherConfig$Repository.
```

**Cause:**
The error is due to incompatibility with the `com.jfrog.artifactory` plugin. In `octopus-release-management`, version `4.24.4` of the plugin is used, which supports the `maven` declaration. However, `octopus-license-gradle-plugin` uses version `5.2.5`, where support for `maven` has been removed.

**Solution:**
- Downgrade the `com.jfrog.artifactory` plugin in `octopus-license-gradle-plugin` to latest `4.x.x` version (`4.33.1`).
- Add a functional test to ensure compatibility with `octopus-release-management`.

**Additional Changes:**
- Renamed all environment variables for testing to use only uppercase. The following environment variables need to be configured for functional tests:
   - `OCTOPUS_LICENSE_MAVEN_PLUGIN_VERSION`
   - `LICENSE_REGISTRY_GIT_REPOSITORY`
   - `OCTOPUS_RELEASE_MANAGEMENT_PLUGIN_VERSION` or `OCTOPUS_RELEASE_MANAGEMENT_GRADLE_PLUGIN_VERSION`

2024-10-04 09:05 UTC, pgorbachev commented on gradle.properties
> +jfrog-artifactory.version=4.33.1
Add comment that 5.x is incompatible with rm-gradle-plugin

2024-10-07 08:15 UTC, pgorbachev commented on ft/src/test/resources/projects/octopus-releng-plugin-compatibility/gradle.properties
> +octopus-release-management.version=2.0.27
Put 1.0 and override it on the test run with actual RM plugin version

2024-10-07 08:16 UTC, pgorbachev requested changes
fix the review

2024-10-08 07:34 UTC, fishinitself approved these changes

2024-10-08 08:25 UTC, pgorbachev commented on ft/src/main/kotlin/org/octopusden/octopus/license/management/plugins/gradle/license/LicensePluginRunner.kt
> +    val octopusReleaseManagementVersion = System.getenv().getOrDefault("octopus-release-management.version", "1.0")
Fail with clear message that either GRADLE_OCTOPUS_RELEASE_MANAGEMENT_PLUGIN_VERSION or octopus-release-management.version should be specified
Don't use not existing 1.0 as default

2024-10-08 08:26 UTC, pgorbachev commented on ft/src/test/resources/projects/octopus-releng-plugin-compatibility/gradle.properties
> +octopus-release-management.version=1.0
keep the value empty in order to push developers to manually specify latest version of RM gradle plugin

2024-10-08 08:26 UTC, pgorbachev requested changes
see comments

2024-10-10 08:39 UTC, pgorbachev commented on ft/src/test/resources/projects/octopus-releng-plugin-compatibility/gradle.properties
> +octopus-release-management.version=
let's remove the parameter because it's not used

2024-10-10 08:41 UTC, pgorbachev requested changes

2024-10-10 08:41 UTC, pgorbachev commented on ft/src/main/kotlin/org/octopusden/octopus/license/management/plugins/gradle/license/LicensePluginRunner.kt
> +const val GRADLE_OCTOPUS_RELEASE_MANAGEMENT_PLUGIN_VERSION_PROPERTY = "octopus-release-management.version"
Leave only upper-case parameters

2024-10-10 08:45 UTC, pgorbachev commented on ft/src/main/kotlin/org/octopusden/octopus/license/management/plugins/gradle/license/LicensePluginRunner.kt
>  const val OCTOPUS_LICENSE_MAVEN_PLUGIN_VERSION = "2.0.8"
Let's remove hard-coded default version

2024-10-10 13:00 UTC, pgorbachev commented on ft/src/main/kotlin/org/octopusden/octopus/license/management/plugins/gradle/license/LicensePluginRunner.kt
> +    val licenseManagementVersion = System.getenv().getOrDefault("LICENSE_MANAGEMENT_VERSION", "1.0-SNAPSHOT")
OCTOPUS_LICENSE_GRADLE_PLUGIN_VERSION

2024-10-11 06:58 UTC, pgorbachev submitted a review, later dismissed

2024-10-14 08:07 UTC, pgorbachev approved these changes

2024-10-14 18:21 UTC, aryabokon approved these changes

2024-10-15 01:32 UTC, merged